name: Security Scan using Snyk
on: 
  push:
    branches: [ 'master' ]
  pull_request: 
    branches: [ 'master' ]
    
jobs:
  security:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write
  
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
